"""remove data1 in product

Revision ID: 43309a528187
Revises: a47ac6bdbde8
Create Date: 2023-04-21 15:14:49.631623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43309a528187'
down_revision = 'a47ac6bdbde8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'data2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('data2', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
