"""remove data in product

Revision ID: 62a6f3800085
Revises: 8565118500bf
Create Date: 2023-04-21 14:46:01.894414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a6f3800085'
down_revision = '8565118500bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
