"""sd

Revision ID: 826193c2ed9b
Revises: 27c043b8d085
Create Date: 2023-04-24 14:39:38.067372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826193c2ed9b'
down_revision = '27c043b8d085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
