"""remove data in product

Revision ID: 8565118500bf
Revises: 8e98f84b3496
Create Date: 2023-04-21 14:33:56.842567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8565118500bf'
down_revision = '8e98f84b3496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('data1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'data1')
    # ### end Alembic commands ###
