"""remove data in product

Revision ID: 8e98f84b3496
Revises: 137e2b1038f8
Create Date: 2023-04-21 14:23:49.400437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e98f84b3496'
down_revision = '137e2b1038f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('data', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
