"""remove category in product table

Revision ID: 96d62539b27f
Revises: 3d7fe6c6c99c
Create Date: 2023-04-24 10:05:35.165732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d62539b27f'
down_revision = '3d7fe6c6c99c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
