"""Initial migration

Revision ID: a07a2897cead
Revises: 704fa8a446e0
Create Date: 2023-04-20 15:51:44.081695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07a2897cead'
down_revision = '704fa8a446e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'hsn_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'dimensions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product', 'dimensions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'hsn_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
