"""remove data1 in product

Revision ID: a47ac6bdbde8
Revises: fbb7250e9d31
Create Date: 2023-04-21 15:14:14.457886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47ac6bdbde8'
down_revision = 'fbb7250e9d31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
