"""remove data1 in product

Revision ID: dc6bf9c3d311
Revises: 43309a528187
Create Date: 2023-04-21 18:11:27.500001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6bf9c3d311'
down_revision = '43309a528187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'brand', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_column('brand', 'category_id')
    # ### end Alembic commands ###
