"""relation migration

Revision ID: f898f1df41ae
Revises: a07a2897cead
Create Date: 2023-04-20 17:20:19.943360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f898f1df41ae'
down_revision = 'a07a2897cead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
