"""remove data1 in product

Revision ID: fbb7250e9d31
Revises: 15cd5b2684c5
Create Date: 2023-04-21 15:02:31.639793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb7250e9d31'
down_revision = '15cd5b2684c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'data1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('data1', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
